name: envHM
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - alsa-lib=1.2.6.1=h7f98852_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38h0a891b7_2
  - asttokens=2.0.8=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - attrs=22.1.0=pyh71513ae_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_10
  - bleach=5.0.1=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.6.15=ha878542_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2022.6.15=py38h578d9bd_0
  - cffi=1.14.6=py38ha65f79e_0
  - curl=7.83.1=h7bff187_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.6=h48d8840_2
  - debugpy=1.6.3=py38hfa26641_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.10.0=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - fftw=3.3.10=nompi_ha7695d1_103
  - flit-core=3.7.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=hca18f0e_0
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=9.5.0=h6c5bc03_16
  - gcc_linux-64=9.5.0=h4258300_10
  - gettext=0.19.8.1=h0b5b191_1005
  - gfortran_impl_linux-64=9.5.0=h3c9b8b6_16
  - gfortran_linux-64=9.5.0=hdb51d14_10
  - glib=2.68.4=h9c3ff4c_0
  - glib-tools=2.68.4=h9c3ff4c_0
  - gmp=6.2.1=h58526e2_0
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.6=he838d99_2
  - gst-plugins-base=1.18.4=h29181c9_0
  - gstreamer=1.18.5=h76c114f_0
  - gxx_impl_linux-64=9.5.0=h6c5bc03_16
  - gxx_linux-64=9.5.0=h43f449f_10
  - harfbuzz=3.0.0=h83ec7ef_1
  - hdf4=4.2.15=h9772cbc_4
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=68.2=h9c3ff4c_0
  - importlib-metadata=4.11.4=py38h578d9bd_0
  - importlib_resources=5.9.0=pyhd8ed1ab_0
  - ipykernel=6.15.1=pyh210e3f2_0
  - ipython=8.4.0=py38h578d9bd_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.1=pyhd8ed1ab_0
  - jack=1.9.18=h8c3723f_1002
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - jsonschema=4.14.0=pyhd8ed1ab_0
  - jupyter=1.0.0=py38h578d9bd_7
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_console=6.4.4=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py38h578d9bd_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.2=pyhd8ed1ab_0
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py38h43d8883_0
  - krb5=1.19.3=h3790be6_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcap=2.64=ha37c62d_0
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=11.1.0=default_ha53f305_1
  - libclang13=14.0.6=default_h3a83d3e_0
  - libcups=2.3.3=h3e49a29_2
  - libcurl=7.83.1=h7bff187_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.13=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.3=h58526e2_2
  - libflac=1.3.4=h27087fc_0
  - libgcc-devel_linux-64=9.5.0=h367e8d2_16
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.68.4=h3e27bee_0
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=16_linux64_openblas
  - libllvm11=11.1.0=hf817b99_3
  - libllvm14=14.0.6=he0ac6c6_0
  - libnetcdf=4.8.0=nompi_hcd642e3_103
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.21=pthreads_h78a6416_2
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h753d276_4
  - libpq=13.5=hd57d9b9_1
  - libsanitizer=9.5.0=hf86b28c_16
  - libsndfile=1.0.31=h9c3ff4c_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.39.2=h753d276_1
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-devel_linux-64=9.5.0=h367e8d2_16
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=h0e0dad5_3
  - libtool=2.4.6=h9c3ff4c_1008
  - libudev1=249=h166bdaf_4
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzip=1.9.2=hc869a4a_1
  - libzlib=1.2.12=h166bdaf_2
  - make=4.3=hd18ef5c_1
  - markupsafe=2.1.1=py38h0a891b7_1
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py38h5c7f4ab_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=0.8.4=py38h497a2fe_1005
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.30=haf5c9bc_0
  - mysql-libs=8.0.30=h28c427c_0
  - nb_conda=2.2.1=unix_6
  - nb_conda_kernels=2.3.1=py38h578d9bd_1
  - nbclient=0.5.13=pyhd8ed1ab_0
  - nbformat=5.4.0=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - notebook=6.4.12=pyha770c72_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - numpy=1.23.2=py38h3a7f9d9_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=1.1.1q=h166bdaf_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.3=py38h47df419_0
  - pandoc=2.19.1=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.48.10=h54213e6_2
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.37=hc3806b6_1
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py38ha3b2c9c_2
  - pip=22.2.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - ply=3.11=py_1
  - portaudio=19.6.0=h57a0ea0_5
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.30=pyha770c72_0
  - prompt_toolkit=3.0.30=hd8ed1ab_0
  - psutil=5.9.1=py38h0a891b7_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.12.3=py38ha8c2ead_4
  - pyrsistent=0.18.1=py38h0a891b7_1
  - python=3.8.8=hffdb5ce_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.1=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2022.2.1=pyhd8ed1ab_0
  - pyzmq=23.2.1=py38hfc09fa9_0
  - qt=5.12.9=hda022c4_4
  - qtconsole=5.3.1=pyhd8ed1ab_0
  - qtconsole-base=5.3.1=pyha770c72_0
  - qtpy=2.2.0=pyhd8ed1ab_0
  - r-abind=1.4_5=r36h6115d3f_1003
  - r-ade4=1.7_13=r36hcdcec82_1001
  - r-ape=5.5=r36h306847c_0
  - r-assertthat=0.2.1=r36h6115d3f_2
  - r-backports=1.2.1=r36hcfec24a_0
  - r-base=3.6.3=hbcea092_8
  - r-base64enc=0.1_3=r36hcfec24a_1004
  - r-caret=6.0_88=r36hcfec24a_0
  - r-checkmate=2.0.0=r36hcdcec82_1
  - r-class=7.3_19=r36hcfec24a_0
  - r-cli=2.5.0=r36hc72bb7e_0
  - r-cluster=2.1.2=r36h859d828_0
  - r-clusterr=1.2.5=r36h306847c_0
  - r-codetools=0.2_18=r36hc72bb7e_0
  - r-colorspace=2.0_1=r36hcfec24a_0
  - r-comprehenr=0.6.7=r36h6115d3f_0
  - r-crayon=1.4.1=r36hc72bb7e_0
  - r-data.table=1.14.0=r36hcfec24a_0
  - r-desc=1.3.0=r36hc72bb7e_0
  - r-digest=0.6.27=r36h03ef668_0
  - r-dotcall64=1.0_1=r36h859d828_0
  - r-dplyr=1.0.6=r36h03ef668_0
  - r-ellipsis=0.3.2=r36hcfec24a_0
  - r-evaluate=0.14=r36h6115d3f_2
  - r-fansi=0.4.2=r36hcfec24a_0
  - r-far=0.6_5=r36h96ca727_0
  - r-fd=1.0_12=r36h580db52_1004
  - r-fields=12.3=r36h859d828_0
  - r-foreach=1.5.1=r36h142f84f_0
  - r-future=1.19.1=r36h6115d3f_0
  - r-future.apply=1.7.0=r36hc72bb7e_0
  - r-generics=0.1.0=r36hc72bb7e_0
  - r-gensa=1.1.7=r36hd1ecc6f_1005
  - r-geometry=0.4.5=r36h0357c0b_1
  - r-ggplot2=3.3.3=r36hc72bb7e_0
  - r-globals=0.14.0=r36hc72bb7e_0
  - r-glue=1.4.2=r36hcfec24a_0
  - r-gmp=0.6_2=r36h03ef668_0
  - r-gower=0.2.2=r36hcdcec82_0
  - r-gridextra=2.3=r36h6115d3f_1003
  - r-gtable=0.3.0=r36h6115d3f_3
  - r-gtools=3.8.2=r36hcdcec82_1
  - r-here=1.0.1=r36hc72bb7e_0
  - r-htmltools=0.5.1.1=r36h03ef668_0
  - r-invgamma=1.1=r36h6115d3f_1
  - r-ipred=0.9_11=r36hcfec24a_0
  - r-irdisplay=1.0=r36hd8ed1ab_0
  - r-irkernel=1.2=r36hc72bb7e_0
  - r-isoband=0.2.4=r36h03ef668_0
  - r-iterators=1.0.13=r36h142f84f_0
  - r-jsonlite=1.7.2=r36hcfec24a_0
  - r-kernsmooth=2.23_20=r36h742201e_0
  - r-labeling=0.4.2=r36h142f84f_0
  - r-lattice=0.20_44=r36hcfec24a_0
  - r-lava=1.6.9=r36hc72bb7e_0
  - r-lhs=1.1.1=r36h1b71b39_0
  - r-lifecycle=1.0.0=r36hc72bb7e_0
  - r-linprog=0.9_2=r36h6115d3f_2
  - r-listenv=0.8.0=r36h6115d3f_1
  - r-loo=2.4.1=r36hc72bb7e_0
  - r-lpsolve=5.6.15=r36hcdcec82_1
  - r-lubridate=1.7.10=r36h03ef668_0
  - r-magic=1.5_9=r36h6115d3f_2
  - r-magrittr=2.0.1=r36hcfec24a_1
  - r-maps=3.3.0=r36hcdcec82_1004
  - r-mass=7.3_54=r36hcfec24a_0
  - r-matrix=1.3_3=r36he454529_0
  - r-matrixstats=0.58.0=r36hcfec24a_0
  - r-mco=1.0_15.1=r36hcdcec82_2
  - r-mgcv=1.8_35=r36he454529_0
  - r-modelmetrics=1.2.2.2=r36h0357c0b_1
  - r-munsell=0.5.0=r36h6115d3f_1003
  - r-mvtnorm=1.1_1=r36h580db52_1
  - r-ncdf4=1.17=r36h5e31ef6_5
  - r-nlme=3.1_152=r36h859d828_0
  - r-nnet=7.3_16=r36hcfec24a_0
  - r-numderiv=2016.8_1.1=r36h6115d3f_3
  - r-pbdzmq=0.3_5=r36h42bf92c_1
  - r-permute=0.9_5=r36h6115d3f_3
  - r-pillar=1.4.4=r36h6115d3f_0
  - r-pkgconfig=2.0.3=r36h6115d3f_1
  - r-pkgload=1.2.1=r36h03ef668_0
  - r-plyr=1.8.6=r36h0357c0b_1
  - r-png=0.1_7=r36hcfec24a_1004
  - r-pracma=2.3.3=r36hc72bb7e_0
  - r-praise=1.0.0=r36h6115d3f_1004
  - r-proc=1.17.0.1=r36h03ef668_0
  - r-prodlim=2019.11.13=r36h0357c0b_1
  - r-purrr=0.3.4=r36hcfec24a_1
  - r-r6=2.5.0=r36hc72bb7e_0
  - r-rappdirs=0.3.3=r36hcfec24a_0
  - r-rcolorbrewer=1.1_2=r36h6115d3f_1003
  - r-rcpp=1.0.6=r36h03ef668_0
  - r-rcpparmadillo=0.10.4.0.0=r36h306847c_0
  - r-rcppprogress=0.4.2=r36h6115d3f_1
  - r-rcpptoml=0.1.7=r36h03ef668_0
  - r-recipes=0.1.16=r36hc72bb7e_0
  - r-repr=1.1.3=r36h785f33e_0
  - r-reshape2=1.4.4=r36h0357c0b_1
  - r-reticulate=1.20=r36h03ef668_0
  - r-rlang=0.4.11=r36hcfec24a_0
  - r-rpart=4.1_15=r36hcfec24a_2
  - r-rprojroot=2.0.2=r36hc72bb7e_0
  - r-rstudioapi=0.13=r36hc72bb7e_0
  - r-scales=1.0.0=r36h0357c0b_1002
  - r-shape=1.4.6=r36ha770c72_0
  - r-spam=2.6_0=r36h52d45c5_0
  - r-squarem=2021.1=r36hc72bb7e_0
  - r-stringi=1.6.2=r36hcabe038_0
  - r-stringr=1.4.0=r36h6115d3f_2
  - r-survival=3.2_11=r36hcfec24a_0
  - r-tensor=1.5=r36h6115d3f_1003
  - r-testthat=2.3.2=r36h0357c0b_1
  - r-tibble=2.1.3=r36hcdcec82_1
  - r-tidyr=1.1.3=r36h03ef668_0
  - r-tidyselect=1.1.1=r36hc72bb7e_0
  - r-timedate=3043.102=r36h6115d3f_1002
  - r-utf8=1.2.1=r36hcfec24a_0
  - r-uuid=0.1_4=r36hcdcec82_1
  - r-vctrs=0.3.8=r36hcfec24a_1
  - r-vegan=2.5_7=r36h52d45c5_0
  - r-viridis=0.6.1=r36hc72bb7e_0
  - r-viridislite=0.4.0=r36hc72bb7e_0
  - r-withr=2.4.2=r36hc72bb7e_0
  - r-xtable=1.8_4=r36h6115d3f_3
  - readline=8.1.2=h0f457ee_0
  - scikit-learn=1.1.2=py38h0b08f9b_0
  - scipy=1.9.0=py38hea3f02b_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - sed=4.8=he412f7d_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.2.0=py38h578d9bd_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.39.2=h4ff8645_1
  - stack_data=0.4.0=pyhd8ed1ab_0
  - statsmodels=0.13.2=py38h71d37f0_0
  - sysroot_linux-64=2.12=he073ed8_15
  - terminado=0.15.0=py38h578d9bd_0
  - testpath=0.6.0=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h27826a3_0
  - tktable=2.10=hb7b940f_3
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.2=py38h0a891b7_0
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.3.0=pyhd8ed1ab_0
  - tzdata=2022c=h191b570_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=4.0.2=pyhd8ed1ab_0
  - xarray=2022.6.0=pyhd8ed1ab_1
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_2
  - zstd=1.5.2=h6239696_4
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - mogp_emulator==0.5.0
